#!/usr/bin/env bash
# vim: ts=8 sts=4 sw=4 et ft=sh

# Copyright (c) 2016-2022, Nicolas Thery (nthery@gmail.com)
#
# Maintain local git branches over sources managed with another SCM.
# See https://github.com/nthery/localgit for details.

# Bail out early if a command exits abnormally.
set -e

progname=$(basename "$0")

commands=""

##############################################################################
# DEBUGGING
##############################################################################

# TODO: Disable when thorougly tested.
debug=1

# Enable shell tracing if debug mode set.
tron()
{
    if (( debug > 0 )); then
        set -x
    fi
}

# Disable shell tracing if debug mode set.
troff()
{
    if (( debug > 0 )); then
        set +x
    fi
}

##############################################################################
# ERROR MANAGEMENT
##############################################################################

error()
{
    echo 1>&2 "$progname: $*"
    exit 1
}

usage()
{
    local code=0
    if [[ -n "$*" ]]; then
        echo -e 1>&2 "$progname: $*\n"
        code=1
    fi
    echo -e 1>&2 "usage: $progname cmd args\n"
    echo -e 1>&2 "The supported commands are:\n"
    echo -e 1>&2 "$commands"
    exit $code
}

##############################################################################
# HELPERS
##############################################################################

expect_topic()
{
    if [[ "$(current_branch)" == "main" ]]; then
        error "should be in topic branch but in main"
    fi
}

expect_main()
{
    if [[ "$(current_branch)" != "main" ]]; then
        error "should be in main branch but in $(current_branch)"
    fi
}

current_branch()
{
    git branch | grep '^\*' | cut -d' ' -f2
}

# Print all files in repo.
all_files()
{
    git ls-tree --full-tree -r main | awk '{print $4}' | grep -vw .lg
}

# Print root of git repo.
git_root() {
    git rev-parse --show-toplevel
}

start_non_local_git_root_creation()
{
    local -r name="$1"

    if [[ -n "$LG_GIT_DIR_PREFIX" ]]; then
        [[ -d "$LG_GIT_DIR_PREFIX" ]] || error "directory not found: $LG_GIT_DIR_PREFIX"
        local -r git_dir="$LG_GIT_DIR_PREFIX/${name}.git"
        [[ ! -d "$git_dir" ]] || error "directory already exists: $git_dir"
        pushd "$LG_GIT_DIR_PREFIX"
    fi
}

# macOS does not have realpath(1) so emulate it.
# Pinched from https://stackoverflow.com/questions/3572030/bash-script-absolute-path-with-os-x
portable_realpath()
{
    local -r path="$1"

    local -r saved_cwd="$(pwd)"

    cd "$(dirname "$path")"
    local link
    link=$(readlink "$(basename "$path")")
    while [[ -n "$link" ]]; do
        cd "$(dirname "$link")"
        link=$(readlink "$(basename "$path")")
    done
    local -r real="$(pwd)/$(basename "$path")"
    cd "$saved_cwd"
    echo "$real"
}

xrealpath()
{
    local -r path="$1"

    if type realpath >/dev/null 2>&1; then
        realpath "$path"
    else
        portable_realpath "$path"
    fi
}

complete_non_local_git_root_creation()
{
    local -r name="$1"

    if [[ -n "$LG_GIT_DIR_PREFIX" ]]; then
        mv .git "${name}.git"
        popd
        local -r git_dir="$LG_GIT_DIR_PREFIX/${name}.git"
        git --git-dir "$git_dir" config core.worktree "$(pwd)"
        echo "gitdir: $(xrealpath "$git_dir")" > .git
    fi
}

parent_dir()
{
    basename "$(pwd)"
}

##############################################################################
# init command
##############################################################################

commands="${commands}init - create local git\n"

lg_init()
{
    local opt
    local name
    name="$(parent_dir)"
    while getopts ":r:n:" opt; do
        case $opt in
            n) name="$OPTARG" ;;
            :) error "option $OPTARG: missing argument" ;;
            *) error "bad option: $OPTARG" ;;
        esac
    done

    shift $(( OPTIND - 1 ))

    [[ ! -r .git ]] || error ".git already exists"

    start_non_local_git_root_creation "$name"

    tron

    git init --initial-branch=main

    # Create dummy initial commit.
    # Failing this initial lg-import from orphan topic branch fails.
    git commit --allow-empty -m 'lg: big bang'

    complete_non_local_git_root_creation "$name"

    # Switch to topic branch.
    git checkout -b dev
}

##############################################################################
# import command
##############################################################################

commands="${commands}import - add file to local git\n"

lg_import()
{
    # Error out if some files do not exist or are already baselined.
    local f
    for f in "$@"; do
        [[ -f "$f" ]] || error "missing file: $f"
        if all_files | grep -q -w "$f"; then
            error "file already baselined: $f"
        fi
    done

    # Error out if some files are not descendants of the repo root.
    local -r root_pattern="$(git_root)/*"
    for f in "$@"; do
        # Intentionally not quoting variables on next line to trigger pattern matching.
        # shellcheck disable=SC2053
        if [[ $(xrealpath "$f") != $root_pattern ]]; then
            error "file not under repo root: $f"
        fi
    done

    expect_topic

    local -r topic=$(current_branch)

    local log="lg: import $*"

    # If commit log too long to fit in 80 columns, first strip directories.
    if (( ${#log} > (80 - 3) )); then
        log="lg: import"
        for f in "$@"; do
            log="$log $(basename "$f")"
        done
    fi

    # If log still too long, truncate it.
    if (( ${#log} > (80 - 3) )); then
        log="${log:0:76}..."
    fi

    tron

    git stash save lg-import: "$*"

    git checkout main

    git add -f "$@"

    # TODO: Sometimes the detection of files already baselined fails because
    # it is flawed: it greps a sequence of repo-relative paths against an
    # arbitrary path that may for example contain '..'.
    # Work around this for the time being by absorbing the "nothing to commit"
    # error to avoid bailing out while in main.
    git commit -m "$log" || true

    git checkout "$topic"

    git rebase main

    git stash pop || true
}

##############################################################################
# sync command
##############################################################################

commands="${commands}sync - rebase local main branch after sync'ing from remote SCM\n"

lg_sync()
{
    expect_main

    local msg="lg: sync"
    if [[ -n "$*" ]]; then
        msg="$msg: $*"
    fi

    tron

    pushd "$(git_root)"
    # shellcheck disable=SC2046
    git add $(all_files)
    popd

    git commit -m "$msg"
}

##############################################################################
# status command
##############################################################################

commands="${commands}status - print status of files in local branches\n"

lg_status()
{
    git status -uno
}

##############################################################################
# log command
##############################################################################

commands="${commands}log - run git log on local topic branch excluding local main\n"

lg_log()
{
    expect_topic
    git log main.. "$@"
}

##############################################################################
# files command
##############################################################################

commands="${commands}files - print files in local topic branch\n"

lg_files()
{
    expect_topic
    local rev="$*"
    if [[ -z "$rev" ]]; then
        rev="main...HEAD"
    fi

    git diff "$rev" | awk '
        function flush(action) { if (file != "") { print action, file; file = "" } }
        /^diff/ { flush("edit"); file = substr($3, 3) }
        /^new file/ { flush("add") }
        /^deleted file/ { flush("delete") }
        END { flush("edit") }
        '
}

##############################################################################
# clone command
##############################################################################

commands="${commands}clone - clone local git repo into another existing source tree\n"

# Validate user-provided source git directory and follow link if .git file provided.
src_git_dir()
{
    local src="$1"
    [[ -n "$src" ]] || error "missing source repo"
    if [[ -f "$src" ]]; then
        local -r remote_dir="$(awk '/^gitdir:/ { print $2 }' "$src")"
        [[ -n "$remote_dir" ]] || error "no gitdir in $src file"
        src="$remote_dir"
    fi
    [[ -d "$src" ]] || error "source git repo does not exist: $src"
    echo "$src"
}

lg_clone()
{
    local opt
    local name
    name="$(parent_dir)"
    while getopts ":n:" opt; do
        case $opt in
            n) name="$OPTARG" ;;
            :) error "option $OPTARG: missing argument" ;;
            *) error "bad option: $OPTARG" ;;
        esac
    done

    shift $(( OPTIND - 1 ))

    local -r src="$(src_git_dir "$1")"

    start_non_local_git_root_creation "$name"

    tron

    git init --initial-branch=main

    complete_non_local_git_root_creation "$name"

    git remote add origin "$src"
    git fetch

    # Sync local main branch with remote one leaving local changes unmodified.
    git reset origin/main
}

##############################################################################
# p4 command and subcommands
##############################################################################

commands="${commands}p4 export - reflect all changes in topic branch into default changelist\n"

p4_root()
{
    type p4 >/dev/null 2>&1 || error "cannot find p4 executable in path"

    local root
    root="$(p4 info | sed -n 's/^Client root: //p')"
    [[ -n "$root" ]] || error "cannot find p4 client root"

    echo "$root"
}

lg_p4_export()
{
    pushd "$(p4_root)"
    lg_files | while read -r f
    do
        # shellcheck disable=SC2086
        p4 $f
    done
    popd
}

lg_p4()
{
    local -r subcmd="$1"
    case "$subcmd" in
        export)
            shift 1
            lg_p4_export "$@" ;;
        *)
            error "unknown or missing subcommand" ;;
    esac
}

##############################################################################
# MAIN PROGRAM
##############################################################################

(( $# > 0 )) || usage "missing command"

cmd=$1
shift

case "$cmd" in
    init)       lg_init "$@" ;;
    i|import)   lg_import "$@" ;;
    sync)       lg_sync "$@" ;;
    s|status)   lg_status "$@" ;;
    f|files)    lg_files "$@" ;;
    log)        lg_log "$@" ;;
    clone)      lg_clone "$@" ;;
    p4)         lg_p4 "$@" ;;
    help)       usage ;;
    *)          usage "unknown command: $cmd" ;;
esac
