#!/usr/bin/env bash

# Copyright (c) 2016, Nicolas Thery (nthery@gmail.com)
# vim: ts=8 sts=4 sw=4 et ft=sh

#
# localgit test suite
#

set -e

source test_lib.bash

readonly lg_bin="$(pwd)/localgit"
[[ -x "$lg_bin" ]] || error "must run from localgit root"

lg()
{
    "$lg_bin" "$@"
}

test_lg_import_creates_commit_in_master()
{
    touch a
    lg init -b topic

    lg import a
    assert "git diff master^..master | grep '^diff --git a/a'"
    assert "git diff master^..master | grep '^new file'"
}

test_lg_import_puts_files_in_log_if_small_enough()
{
    touch a b c
    lg init -b topic

    lg import a b c
    assert 'git log --oneline master^..master | grep -q "lg: import a b c$"'
}

test_lg_import_truncates_file_in_log_if_too_long()
{
    touch a_very_very_longish_file_name_that_is_way_too_big_to_fit_in_commit_log_subject
    lg init -b topic

    lg import a_very_very_longish_file_name_that_is_way_too_big_to_fit_in_commit_log_subject
    assert 'git log --oneline master^..master | grep -q "lg: import a_very_very_longish.*\.\.\.$"'
}

test_lg_import_strips_dirnames_in_log_if_too_long()
{
    mkdir -p a/very/very/longish/file/path/that/is/way/too/big/to/fit/in/commit/log/subject
    touch a/very/very/longish/file/path/that/is/way/too/big/to/fit/in/commit/log/subject/a
    touch b

    lg init -b topic

    lg import a/very/very/longish/file/path/that/is/way/too/big/to/fit/in/commit/log/subject/a b
    assert 'git log --oneline master^..master | grep -q "lg: import a b$"'
}

test_lg_files_prints_added_edited_removed_files()
{
    touch a b
    lg init -b topic

    lg import a
    echo AAA > a
    git commit -am 'edit a'

    lg import b
    git rm b
    git commit -am 'rm b'

    touch c
    git add c
    git commit -am 'add c'

    lg files > lg_files.out
    assert "(( $(wc -l <lg_files.out) == 3 ))"
    assert "grep '^edit a$' lg_files.out"
    assert "grep '^rm b$' lg_files.out"
    assert "grep '^add c$' lg_files.out"
}

run_tests "$@"
